### ISSUE TITLE
Need to specify frames per video

### ISSUE THREAD

**Issue by chris-boson** [ferreirafabio/video2tfrecord#1]
Is it possible to modify so it just automatically grabs the maximum number of frames per video?

On a side note, try to follow the Google Python Style Guide (https://google.github.io/styleguide/pyguide.html) and I recommend you refactor this code into classes.

**Comment by ferreirafabio** [comment]
Hi chris-boson,
thank you for your feedback! Unfortunately, this feature is not yet implemented. I'm currently a bit too busy to improve the package with the requested functionality but I'd like to invite you to implement it and pull-request your update (also in regards of the Google Python style guide). 

Please also note that this piece of code originated from a project with a limited time frame and thus, circumstances didn't allow a feature-rich implementation in accordance to a style guide.
