### ISSUE TITLE
How about including the audio information and then write to the same tfRecords? 

### ISSUE THREAD

**Issue by tuffr5** [ferreirafabio/video2tfrecord#12]

**Comment by tuffr5** [comment]
are tfRecords files capable applying JSON format？ If so，I think it wouldn't be a problem to do this combination.

**Comment by ferreirafabio** [comment]
Hi,
I don't understand the question; what does "applying JSON format to tfrecords" mean exactly?

**Comment by tuffr5** [comment]
Hello, it's like 
{a' : 1,
 'b' : {'c' : 2, 'd' : 3}
} . Can this format be stored in tfRecords?

**Comment by ferreirafabio** [comment]
yes, everything that can be converted into a byte string can be stored in tfrecords.

**Comment by tuffr5** [comment]
OK, thanks. It looks like I have to get more familiar with the  tfRecords, and try to implement my idea.
