### ISSUE TITLE
AssertionError: something went wrong during video to numpy conversion

### ISSUE THREAD

**Issue by rahvlrawat** [ferreirafabio/video2tfrecord#22]
Hi,
While running it on colab  I am getting the assertion error.
`---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-14-270cbf453c5a> in <module>()
      1 from video2tfrecord import convert_videos_to_tfrecord
      2 
----> 3 convert_videos_to_tfrecord('/content/drive/My Drive/XVD/videos/','content', 3, 10, "*.mp4")

/usr/local/lib/python3.6/dist-packages/video2tfrecord/video2tfrecord.py in convert_videos_to_tfrecord(source_path, destination_path, n_videos_in_record, n_frames_per_video, file_suffix, dense_optical_flow, width, height, color_depth, video_filenames)
    174       total_batch_number = int(math.ceil(len(filenames) / n_videos_in_record))
    175     print('Batch ' + str(i + 1) + '/' + str(total_batch_number) + " completed")
--> 176     assert data.size != 0, 'something went wrong during video to numpy conversion'
    177     save_numpy_to_tfrecords(data, destination_path, 'batch_',
    178                             n_videos_in_record, i + 1, total_batch_number,

AssertionError: something went wrong during video to numpy conversion

Any idea as to what might be causing this and how to fix it?

**Comment by rahvlrawat** [comment]
used this and it worked:

tf.compat.v1.flags.DEFINE_string('f', '', 'kernel')

**Comment by ferreirafabio** [comment]
Thank you. Please feel free to pull request that change.
