### ISSUE TITLE
Unknown command line flag 'f'

### ISSUE THREAD

**Issue by jimdowling** [ferreirafabio/video2tfrecord#3]
Hi. 
I am trying to run the Unit Test with the included 2 videos with 
    convert_videos_to_tfrecord(source_path=localdir, destination_path=local_out,
                               n_videos_in_record=n_videos_per_record,
                               n_frames_per_video=n_frames,
                               dense_optical_flow=True,
                               width=width,
                               height=height,
                               file_suffix="*.mp4")
 and I get this error:

<ipython-input-19-c2d3676c13fe> in create(self)
      7                                width=width,
      8                                height=height,
----> 9                                file_suffix="*.mp4")
     10 
     11     filenames = gfile.Glob(os.path.join(local_out, "*.tfrecords"))

/srv/hops/anaconda/anaconda/envs/demo_tensorflow_jdowlin0/lib/python3.6/site-packages/video2tfrecord/video2tfrecord.py in convert_videos_to_tfrecord(source_path, destination_path, n_videos_in_record, n_frames_per_video, file_suffix, dense_optical_flow, width, height, color_depth, video_filenames)
    174       total_batch_number = int(math.ceil(len(filenames) / n_videos_in_record))
    175     print('Batch ' + str(i + 1) + '/' + str(total_batch_number) + " completed")
--> 176     assert data.size != 0, 'something went wrong during video to numpy conversion'
    177     save_numpy_to_tfrecords(data, destination_path, 'batch_',
    178                             n_videos_in_record, i + 1, total_batch_number,

AssertionError: something went wrong during video to numpy conversion

Any ideas what this could be?

**Comment by ferreirafabio** [comment]
Hi Jim,

where does 'Unknown command line flag 'f'' appear? I can't see it in the stack trace. Also, which Python version and on which OS are you working on?

**Comment by jimdowling** [comment]
'Unknown command line flag 'f'' 
gets printed to stdout
I am using python 3.6 and centos 7.2

**Comment by ferreirafabio** [comment]
I see. Did you make sure to use the requirements specified in https://github.com/ferreirafabio/video2tfrecord/blob/master/requirements.txt ?
Reading [1], I believe this might be a tensorflow issue. According to user taixhi, you could try this:

"I solved this issue by adding the line:
tf.app.flags.DEFINE_string('f', '', 'kernel')
what this essentially does is that it creates a flag f. This is effective as jupyter notebook supplies a flag "-f" to pass a name for a JSON file, likely for the kernel."

[1] https://github.com/tensorflow/tensorflow/issues/17702

**Comment by jimdowling** [comment]
@ferreirafabio  - great find, thanks!
Yes, adding this line worked:
tf.app.flags.DEFINE_string('f', '', 'kernel')

**Comment by jimdowling** [comment]
I should add i was using tensorflow 1.8.
