### ISSUE TITLE
Problem in numpy

### ISSUE THREAD

**Issue by Hansxsourse** [ferreirafabio/video2tfrecord#4]
I use video2record to deal with some short video, I want to turn them into tfrecord then I can input them into tensorflow. Then I use videorecord on github: https://github.com/ferreirafabio/video2tfrecord But when I run it, the error said numpy wrong here are my code(python):

from video2tfrecord import convert_videos_to_tfrecord

convert_videos_to_tfrecord(source_path="video", destination_path="video", n_videos_in_record= 1 , n_frames_per_video = 5 , file_suffix="*.mp4") 
here are the error:

AssertionError Traceback (most recent call last) in () 1 from video2tfrecord import convert_videos_to_tfrecord 2 ----> 3 convert_videos_to_tfrecord(source_path="video", destination_path="video", n_videos_in_record= 1 , n_frames_per_video = 5 , file_suffix="*.mp4")

/usr/local/lib/python3.6/dist-packages/video2tfrecord/video2tfrecord.py in convert_videos_to_tfrecord(source_path, destination_path, n_videos_in_record, n_frames_per_video, file_suffix, dense_optical_flow, width, height, color_depth, video_filenames) 174 total_batch_number = int(math.ceil(len(filenames) / n_videos_in_record)) 175 print('Batch ' + str(i + 1) + '/' + str(total_batch_number) + " completed") --> 176 assert data.size != 0, 'something went wrong during video to numpy conversion' 177 save_numpy_to_tfrecords(data, destination_path, 'batch_', 178 n_videos_in_record, i + 1, total_batch_number,

AssertionError: something went wrong during video to numpy conversion

**Comment by ferreirafabio** [comment]
What video type are you dealing with? Please report codec, duration, fps etc. for example with `ffmpeg -i` [1]

[1] https://www.commandlinefu.com/commands/view/2207/get-video-information-with-ffmpeg

**Comment by Hansxsourse** [comment]
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1004961276.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     encoder         : Lavf57.83.100
>     comment         : Meipai[HUAWEI][7.0|24][HUAWEI NXT-TL00][Resolution:1920*1080][7.5.0][Accelerate:1.0][Filter:{圆舞曲:0.8}]
>   Duration: 00:00:10.78, start: 0.000000, bitrate: 792 kb/s
>     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 960x540, 685 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 96 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler


here is one of the dataset video info.

**Comment by ferreirafabio** [comment]
Hi,

Assuming it's a codec issue, OpenCV might be having problems with decoding the video stream with the codecs installed on your system. Have you tried running test.py in the repisotiry with the example videos checked in? Do you get the same error? If that works fine, the problem ought to be related to a codec/system issue rather than a video2tfrecord implementation error. Could you please check that?
Thanks!

**Comment by Hansxsourse** [comment]
Thanks for your reply
I can run example video successfully, maybe I'll go to read some doc about OpenCV and check it.
Thanks

**Comment by ferreirafabio** [comment]
Sure!
I'd be interested in your findings! Please let me know!
