### ISSUE TITLE
High memory use

### ISSUE THREAD

**Issue by AlvaroCavalcante** [ferreirafabio/video2tfrecord#40]
Hello guys, I found another issue when trying to use the project in my context. The problem is that I'm running the code on a computer with only 8GB of RAM, and I would like to put as many videos as possible in each TFrecord file. 

It turns out that the memory consumption increases as the program runs, until the point that it just crashes. It turns out that the "data" array keeps occupying memory even when a new iteration of the for loop starts...

To solve this, I basically added the following lines of code: 
```
data = None

for i, batch in enumerate(filenames_split):
     if data is not None:
          data = None
```
When assigning the "data" array to None the memory is released instantly. With this simple modification, I'm able to put about 140 into each file! 

Do you think that I could create a PR with this modification?

**Comment by ferreirafabio** [comment]
Hi Alvaro,

thanks a lot for taking care of this. Feel free to create a PR and I'll check it.

**Comment by AlvaroCavalcante** [comment]
Thanks @ferreirafabio, created!
