### ISSUE TITLE
OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by fascinet** [ferreirafabio/video2tfrecord#6]
![Screenshot (116)](https://user-images.githubusercontent.com/33225187/57772546-4ff4ee00-7733-11e9-8ed6-a1723a67acad.png)
Video and Record are two folders and video contains a "mp4 file".
It take almost 15 min to show the error

**Comment by danielbraun89** [comment]
I have the same problem error: 

cv2.error("OpenCV(3.4.4) C:\\projects\\opencv-python\\opencv\\modules\\imgproc\\src\\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'\n")

**Comment by danielbraun89** [comment]
The program crash even after installing the exact opencv version specified in the requirements.txt file (opencv-python==3.4.0.12),

the error code however, changed to:

`OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cv::cvtColor, file C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp, line 11079`

**Comment by fascinet** [comment]
@ferreirafabio  Have you any idea how to resolve this error or any other way for the conversion?

**Comment by danielbraun89** [comment]
I went ahead and debugged the code, here are my conclusions: The problems coming from 

1. 
`video2tfrecord.py:291`

`frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)`
No "is frame is None" check is being done.
This is causing the original crash w

2.
`video2tfrecord.py:294`

`stop, cap, steps, prev_frame_none, frames_counter = repeat_image_retrieval(
            cap, file_path, take_all_frames, steps, frame, prev_frame_none,
            frames_counter)`

This was probably written for older opencv signature, the new one require the video as a parameter, (and henceforth returns tuple of size 6 and not 5)

3. 
No break check or frames_counter increase at
`video2tfrecord.py: 301`
Causing an infinite loop...

4. 
`video2tfrecord.py: 294`
Using the frame_counter name as unpack variable is overriding the internal counter and again causing an infinite loop...

5. 
`video2tfrecord.py: 294`
Using the cap name as unpack variable and overriding the original cap. 
If the cap is being set to None the program again crashes at 
`video2tfrecord.py: 338`

6.

This may be a bug, and maybe not. Im not sure what is the appropriate behavior but in 
`video2tfrecord.py: 301
`
It seems `video[frames_counter, :, :, :].fill(0) ` would be more logical than to erase the whole video.

@fascinet  I have pushed this changes into a fork: [https://github.com/danielbraun89/video2tfrecord](https://github.com/danielbraun89/video2tfrecord)

you can just use your own pip installed version and replace the content of [https://github.com/danielbraun89/video2tfrecord/blob/master/video2tfrecord.py](https://github.com/danielbraun89/video2tfrecord/blob/master/video2tfrecord.py)
with the video2tfrecord.py that is being used in your installed package.

also I have tested it in the latest opencv, I recommend running a 
`pip install opencv-python -U` 
and disregard the requirements.txt opencv version until the official fix will arrive

**Comment by fascinet** [comment]
Thank you for your reply. It worked very well BTW Great Observation.

**Comment by ferreirafabio** [comment]
Thank you for these findings and for reporting them. Would you be interested in creating a pull request such that all users would benefit from your bugfixes?

**Comment by ferreirafabio** [comment]
Thank you all for your support. The suggestion have now been merged into the master.
